# Generated by Django 4.1.3 on 2022-11-09 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_contratacao', models.DateField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='funcionarios.departamento')),
            ],
        ),
    ]
